### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Anslem27** [Klairm/flutter-spotify-downloader#1]
### App seems not to work at all, even after adding the link
__just plain,no response__
![Screenshot_20220914-152710](https://user-images.githubusercontent.com/89728185/190153404-ce6057cf-5e6f-4a38-bff7-d228e6d481fe.jpg)

**Comment by Klairm** [comment]
have you hit "enter" button after pasting the link?

**Comment by Anslem27** [comment]
> have you hit "enter" button after pasting the link?

Okay now seems to be working, think there was a delay in requesting for storage permission, and after pasting link was probably waiting for maybe a circular progress indicator. But after pasting the url, it takes some time and everything works as expected

**Comment by Klairm** [comment]
> > have you hit "enter" button after pasting the link?
> 
> Okay now seems to be working, think there was a delay in requesting for storage permission, and after pasting link was probably waiting for maybe a circular progress indicator. But after pasting the url, it takes some time and everything works as expected

ye I should work a little more in the UI honestly xD but glad it's working
